### PR TITLE
Added general guidelines

### PR DESCRIPTION
**Pull request by rchampourlier**
- Enriched the README with general guidelines from the Google Docs file (nice work by the way :ok_hand:).
- Added basic TODO to the README.
- Other minor changes to the README.

### CODE REVIEW

**Comment by mru2** [comment]
:+1:

**Comment by mkou** [comment]
:+1:

**Comment by pinouchon** [comment]
I really want jsLint installed (so we need a linter for coffee ?).
And also talk about how we organize javascripts

Besides that, :+1:

**Comment by rchampourlier** [comment]
@pinouchon Your future PR is welcomed ;)

**Comment by bakster** [comment]
:+1:

**Comment by Poilon** [comment]
:+1:

**Pull request merged**
